[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

[fmt]
multiline_func_header = "params_first"

[lint]
exclude_lints = ["screaming-snake-case-immutable"]
