[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 20000

[fmt]
multiline_func_header = "params_first"

[lint]
exclude_lints = ["screaming-snake-case-immutable"]
